In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn import metrics

In [12]:
pipe = make_pipeline(
    SimpleImputer(), StandardScaler(), MLPClassifier(max_iter=1000)
)

In [13]:
nb_train_dataset_path = 'C:/Users/katsa/OneDrive/Jupyter_files/shallow_models_cic_nb15/nb_all_feat_train_dataset.csv'
nb_train_dataset = pd.read_csv(nb_train_dataset_path)
nb_train_dataset.head()

,sport,dsport,dur,sbytes,dbytes,sttl,dttl,sloss,dloss,Sload,...,service_ftp-data,service_http,service_irc,service_pop3,service_radius,service_smtp,service_snmp,service_ssh,service_ssl,Label
0,1661.0,44864.0,0.068378,320,1922,31,29,1,2,3.123812e+04,...,1,0,0,0,0,0,0,0,0,BENIGN
1,1043.0,53.0,0.000018,114,0,254,0,0,0,2.533333e+07,...,0,0,0,0,0,0,0,0,0,ATTACK
2,20206.0,22035.0,0.030012,2438,20006,31,29,7,13,6.328136e+05,...,0,0,0,0,0,0,0,0,0,BENIGN
3,23828.0,53.0,0.001144,146,178,31,29,0,0,5.104895e+05,...,0,0,0,0,0,0,0,0,0,BENIGN
4,30178.0,27470.0,0.131310,4326,61786,31,29,7,30,2.600259e+05,...,0,0,0,0,0,0,0,0,0,BENIGN

In [14]:
nb_test_dataset_path = 'C:/Users/katsa/OneDrive/Jupyter_files/shallow_models_cic_nb15/nb_all_feat_test_dataset.csv'
nb_test_dataset = pd.read_csv(nb_test_dataset_path)
nb_test_dataset.head()

,sport,dsport,dur,sbytes,dbytes,sttl,dttl,sloss,dloss,Sload,...,service_ftp-data,service_http,service_irc,service_pop3,service_radius,service_smtp,service_snmp,service_ssh,service_ssl,Label
0,57395.0,53.0,0.001089,130,162,31,29,0,0,4.775023e+05,...,0,0,0,0,0,0,0,0,0,BENIGN
1,36388.0,80.0,0.282741,912,268,254,252,2,1,2.322974e+04,...,0,1,0,0,0,0,0,0,0,ATTACK
2,37595.0,5190.0,0.006367,1920,4312,31,29,6,6,2.303126e+06,...,0,0,0,0,0,0,0,0,0,BENIGN
3,29983.0,111.0,0.087319,568,320,31,29,0,0,3.902930e+04,...,0,0,0,0,0,0,0,0,0,BENIGN
4,10238.0,53.0,0.001062,146,178,31,29,0,0,5.499058e+05,...,0,0,0,0,0,0,0,0,0,BENIGN

In [15]:
X_train = nb_train_dataset.drop('Label', axis=1)
y_train = nb_train_dataset['Label']

X_test = nb_test_dataset.drop('Label', axis=1)
y_test = nb_test_dataset['Label']

In [16]:
pipe.fit(X_train.to_numpy(), y_train.to_numpy())
predictions = pipe.predict(X_test.to_numpy())
print(metrics.accuracy_score(y_test.to_numpy(), predictions))
print(metrics.classification_report(y_test.to_numpy(), predictions))

0.9906990019881499
              precision    recall  f1-score   support

      ATTACK       0.95      0.98      0.96     12859
      BENIGN       1.00      0.99      0.99     88743

    accuracy                           0.99    101602
   macro avg       0.97      0.99      0.98    101602
weighted avg       0.99      0.99      0.99    101602

In [17]:
import joblib
joblib.dump(pipe, "MLPmodel")
joblib.dump(pipe[1], "scaler")

['scaler']